const students = [
  {
    id: 1,
    name: "Murtuza",
    className: "Mechanical Engineering",
    result: "Pass",
    rollNumber: "ME-101",
    attendance: 185,
  },
  {
    id: 2,
    name: "John Smith",
    className: "Computer Science",
    result: "Pass",
    rollNumber: "CS-102",
    attendance: 192,
  },
  {
    id: 3,
    name: "Emma Wilson",
    className: "Artificial Intelligence",
    result: "Fail",
    rollNumber: "AI-103",
    attendance: 130,
  },
  {
    id: 4,
    name: "David Miller",
    className: "Cyber Security",
    result: "Pass",
    rollNumber: "CY-104",
    attendance: 176,
  },
  {
    id: 5,
    name: "Sophia Davis",
    className: "Data Science",
    result: "Pass",
    rollNumber: "DS-105",
    attendance: 188,
  },
  {
    id: 6,
    name: "Michael Brown",
    className: "Mechanical Engineering",
    result: "Fail",
    rollNumber: "ME-106",
    attendance: 120,
  },
  {
    id: 7,
    name: "Olivia Taylor",
    className: "Computer Science",
    result: "Pass",
    rollNumber: "CS-107",
    attendance: 198,
  },
  {
    id: 8,
    name: "James Anderson",
    className: "Artificial Intelligence",
    result: "Pass",
    rollNumber: "AI-108",
    attendance: 182,
  },
  {
    id: 9,
    name: "Isabella Thomas",
    className: "Cyber Security",
    result: "Pass",
    rollNumber: "CY-109",
    attendance: 194,
  },
  {
    id: 10,
    name: "William Jackson",
    className: "Data Science",
    result: "Fail",
    rollNumber: "DS-110",
    attendance: 140,
  },
];

export default students;

